export enum ECategoryTeam {
  SUB13WOAN = "SUB 13 FEMININO",
  SUB13MEN = "SUB 13 MASCULINO",
  SUB15WOAN = "SUB 15 FEMININO",
  SUB15MEN = "SUB 15 MASCULINO",
  SUB18WOAN = "SUB 18 FEMININO",
  SUB18MEN = "SUB 18 MASCULINO",
  OPENMEN = "ABERTO MASCULINO",
  OPENWOAN = "ABERTO FEMININO",
}
